apiVersion: v1
kind: Service
metadata:
  name: notify
spec:
  selector:
    name: notify
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "metrics"
      port: 9090
      targetPort: 9090
