apiVersion: v1
kind: Service
metadata:
  name: portals
spec:
  selector:
    name: portals
  type: NodePort
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "prometheus"
      port: 9090
      targetPort: 9090
      nodePort: 32023
