apiVersion: v1
kind: Service
metadata:
  name: portals
spec:
  selector:
    name: portals
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "metrics"
      port: 9090
      targetPort: 9090