apiVersion: v1
kind: Service
metadata:
  name: processings
spec:
  selector:
    name: processings
  ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    - name: "metrics"
      port: 9090
      targetPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: processings-worker
spec:
  selector:
    name: processings-worker
  ports:
    - name: "metrics"
      port: 9090
      targetPort: 9090