apiVersion: v1
kind: Service
metadata:
  name: simple-directory
spec:
  type: NodePort
  selector:
    name: simple-directory
  ports:
    - name: "auth"
      port: 8080
      targetPort: 8080
      nodePort: 32600

    - name: "mail"
      port: 1080
      targetPort: 1080
      nodePort: 31080
