apiVersion: apps/v1
kind: Deployment
metadata:
  name: capture
spec:
  replicas: 1
  selector:
    matchLabels:
      name: capture
  template:
    metadata:
      labels:
        name: capture
    spec:
      containers:
        - name: capture
          image: koumoul/capture:1
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: base-url
            - name: DIRECTORY_URL
              value: $(BASE_URL)/simple-directory
            - name: PRIVATE_DIRECTORY_URL
              value: http://simple-directory:8080
            - name: PUBLIC_URL
              value: $(BASE_URL)/capture

          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
