apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fair-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      name: data-fair-worker
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: data-fair-worker
    spec:
      containers:
        - image: ghcr.io/data-fair/data-fair:3
          name: data-fair-worker
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: base-url

            - name: MODE
              value: worker
            - name: DEBUG
              value: upgrade*
            - name: PUBLIC_URL
              value: $(BASE_URL)/data-fair
            - name: DIRECTORY_URL
              value: $(BASE_URL)/simple-directory
            - name: PRIVATE_DIRECTORY_URL
              value: http://simple-directory:8080
            - name: OPENAPI_VIEWER_URL
              value: $(BASE_URL)/api-doc/

            - name: ES_HOST
              value: elasticsearch:9200
            - name: MONGO_URL
              value: mongodb://mongo:27017/data-fair

            - name: CAPTURE_URL
              value: $(BASE_URL)/capture
            - name: NOTIFY_URL
              value: $(BASE_URL)/notify
            - name: PRIVATE_NOTIFY_URL
              value: http://notify:8080

            - name: SECRET_NOTIFICATIONS
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: secret

            - name: THUMBOR_KEY
              value: $(SECRET_NOTIFICATIONS)
            - name: THUMBOR_URL
              value: $(BASE_URL)/thumbor/

          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /data
              name: data-fair-data

      volumes:
        - name: data-fair-data
          persistentVolumeClaim:
            claimName: data-fair-data
