apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-fair
spec:
  replicas: 1
  selector:
    matchLabels:
      name: data-fair
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: data-fair
        scrapeMetrics: 'true'
    spec:
      containers:
        - image: ghcr.io/data-fair/data-fair:3
          name: data-fair
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: base-url

            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: mongo-host

            - name: ELASTICSEARCH_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: elasticsearch-host

            - name: MODE
              value: server
            - name: DEBUG
              value: upgrade*
            - name: PUBLIC_URL
              value: $(BASE_URL)/data-fair
            - name: DIRECTORY_URL
              value: $(BASE_URL)/simple-directory
            - name: PRIVATE_DIRECTORY_URL
              value: http://simple-directory:8080
            - name: OPENAPI_VIEWER_URL
              value: $(BASE_URL)/api-doc/

            - name: ES_HOST
              value: $(ELASTICSEARCH_HOST):9200

            - name: MONGO_URL
              value: mongodb://$(MONGO_HOST):27017/data-fair

            - name: CAPTURE_URL
              value: $(BASE_URL)/capture/
            - name: NOTIFY_URL
              value: $(BASE_URL)/notify
            - name: PRIVATE_NOTIFY_URL
              value: http://notify:8080

            - name: SECRET_IDENTITIES
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: secret
            - name: SECRET_NOTIFICATIONS
              value: $(SECRET_IDENTITIES)
            - name: THUMBOR_KEY
              value: $(SECRET_IDENTITIES)
            - name: THUMBOR_URL
              value: $(BASE_URL)/thumbor/

            - name: EXTRA_NAV_ITEMS
              value: '[{"id": "processings","can":"contrib", "iframe": "/processings/processings", "icon": "mdi-cog-transfer-outline", "title": "Traitements périodiques"},{"id": "portal","iframe": "/portals/manager/portals", "icon": "mdi-presentation", "title": "Portails"},{"id": "metrics","iframe": "/metrics/embed/home", "icon": "mdi-chart-bar", "title": "Audience", "subtitle": "Téléchargements, API"}]'

            - name: EXTRA_ADMIN_NAV_ITEMS
              value: '[{"id": "processings","iframe": "/processings/admin/plugins", "icon": "mdi-cog-transfer-outline", "title": "Traitements périodiques"},{"id": "portal","iframe": "/portals/manager/admin", "icon": "mdi-presentation", "title": "Portails"}]'

          ports:
            - containerPort: 8080
            - name: metrics
              containerPort: 9090
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /data
              name: data-fair-data

      volumes:
        - name: data-fair-data
          persistentVolumeClaim:
            claimName: data-fair-data
