apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metrics
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: metrics
    spec:
      containers:
        - image: ghcr.io/data-fair/metrics:0
          name: metrics
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: base-url

            - name: PUBLIC_URL
              value: $(BASE_URL)/metrics/
            - name: DIRECTORY_URL
              value: $(BASE_URL)/simple-directory/
            - name: PRIVATE_DIRECTORY_URL
              value: http://simple-directory:8080

            - name: MONGO_URL
              value: mongodb://mongo:27017/processings

          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
