apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metrics
  template:
    metadata:
      labels:
        name: metrics
        scrapeMetrics: 'true'
    spec:
      containers:
        - image: ghcr.io/data-fair/metrics:0
          name: metrics
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: base-url
                  
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: mongo-host

            - name: PUBLIC_URL
              value: $(BASE_URL)/metrics
              
            - name: DIRECTORY_URL
              value: $(BASE_URL)/simple-directory
            - name: PRIVATE_DIRECTORY_URL
              value: http://simple-directory:8080

            - name: MONGO_URL
              value: mongodb://$(MONGO_HOST):27017/processings

            - name: SYSLOG_SECRET
              value: syslog_secret

          ports:
            - name: metrics
              containerPort: 9090
            - name: http
              containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
