apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
        - image: nginx:1.21.6-alpine
          name: nginx
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - name: default-conf
              mountPath: /etc/nginx/conf.d
              readOnly: true
      volumes:
        - name: default-conf
          configMap:
            name: nginx-conf
