apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify
spec:
  replicas: 1
  selector:
    matchLabels:
      name: notify
  template:
    metadata:
      labels:
        name: notify
        scrapeMetrics: 'true'
    spec:
      containers:
        - image: ghcr.io/data-fair/notify:3
          name: notify
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: base-url

            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: mongo-host

            - name: PUBLIC_URL
              value: $(BASE_URL)/notify
            - name: DIRECTORY_URL
              value: $(BASE_URL)/simple-directory

            - name: MONGO_URL
              value: mongodb://$(MONGO_HOST):27017/notify

            - name: OPENAPI_VIEWER_URL
              value: $(BASE_URL)/api-doc/
            - name: PRIVATE_DIRECTORY_URL
              value: http://simple-directory:8080

            - name: SECRET_IDENTITIES
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: secret
            - name: SECRET_NOTIFICATIONS
              value: $(SECRET_IDENTITIES)
            - name: SECRET_SENDMAILS
              value: $(SECRET_IDENTITIES)

          ports:
            - name: metrics
              containerPort: 9090
            - name: notify
              containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
