apiVersion: apps/v1
kind: Deployment
metadata:
  name: openapi-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: openapi-viewer
  strategy: {}
  template:
    metadata:
      labels:
        name: openapi-viewer
    spec:
      containers:
        - image: koumoul/openapi-viewer:1
          name: openapi-viewer
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
