apiVersion: apps/v1
kind: Deployment
metadata:
  name: portals
spec:
  replicas: 1
  selector:
    matchLabels:
      name: portals
  template:
    metadata:
      labels:
        name: portals
        scrapeMetrics: 'true'
    spec:
      containers:
        - image: ghcr.io/data-fair/portals:1
          name: portals
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: base-url

            - name: PUBLIC_URL
              value: $(BASE_URL)/portals
            - name: DIRECTORY_URL
              value: $(BASE_URL)/simple-directory
            - name: PRIVATE_DIRECTORY_URL
              value: http://simple-directory:8080
            - name: DATAFAIR_URL
              value: $(BASE_URL)/data-fai
            - name: NOTIFY_URL
              value: $(BASE_URL)/notify
            - name: PRIVATE_NOTIFY_URL
              value: http://notify:8080
            - name: OPENAPIVIEWER_URL
              value: $(BASE_URL)/api-doc/

            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: mongo-host

            - name: SECRET_IDENTITIES
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: secret
            - name: THUMBOR_KEY
              value: $(SECRET_IDENTITIES)
            - name: THUMBOR_URL
              value: $(BASE_URL)/thumbor

          ports:
            - name: "http"
              containerPort: 8080
            - name: "metrics"
              containerPort: 9090
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /webapp/data
              name: portals-data

      volumes:
        - name: portals-data
          persistentVolumeClaim:
            claimName: portals-data
