apiVersion: apps/v1
kind: Deployment
metadata:
  name: portals
spec:
  replicas: 1
  selector:
    matchLabels:
      name: portals
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: portals
    spec:
      containers:
        - image: ghcr.io/data-fair/portals:1
          name: portals
          env:
            - name: BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: base-url

            - name: PUBLIC_URL
              value: $(BASE_URL)/portals/
            - name: DIRECTORY_URL
              value: $(BASE_URL)/simple-directory/
            - name: PRIVATE_DIRECTORY_URL
              value: http://simple-directory:8080
            - name: DATAFAIR_URL
              value: $(BASE_URL)/data-fair/
            - name: NOTIFY_URL
              value: $(BASE_URL)/notify
            - name: PRIVATE_NOTIFY_URL
              value: http://notify:8080
            - name: OPENAPIVIEWER_URL
              value: $(BASE_URL)/api-doc/

            - name: MONGO_HOST
              value: mongo

            - name: SECRET_IDENTITIES
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: secret
            - name: THUMBOR_KEY
              value: $(SECRET_IDENTITIES)
            - name: THUMBOR_URL
              value: $(BASE_URL)/thumbor/

          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /data
              name: data-fair-data

      volumes:
        - name: data-fair-data
          persistentVolumeClaim:
            claimName: data-fair-data
