apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-directory
spec:
  replicas: 1
  selector:
    matchLabels:
      name: simple-directory
  template:
    metadata:
      labels:
        name: simple-directory
    spec:
      containers:
        - env:
            - name: ADMINS
              value: '["admin@test.com"]'
            - name: HOME_PAGE
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: base-url
            - name: LIST_ENTITIES_MODE
              value: admin
            - name: MAILDEV_ACTIVE
              value: "true"
            - name: MAILDEV_URL
              value: $(HOME_PAGE)/mails/
            - name: NOTIFY_URL
              value: $(HOME_PAGE)/notify/
            - name: PASSWORDLESS
              value: "false"
            - name: PRIVATE_NOTIFY_URL
              value: http://notify:8080
            - name: PUBLIC_URL
              value: $(HOME_PAGE)/simple-directory
            - name: ROLES_DEFAULTS
              value: '["admin","contrib","user"]'
            - name: SECRET_NOTIFICATIONS
              valueFrom:
                configMapKeyRef:
                  name: config-global
                  key: secret
            - name: SECRET_SENDMAILS
              value: $(SECRET_NOTIFICATIONS)
            - name: STORAGE_MONGO_URL
              value: mongodb://mongo:27017/simple-directory
            - name: USER_SELF_DELETE
              value: "true"
          image: ghcr.io/data-fair/simple-directory:4
          command: ["/webapp/node_modules/.bin/nodemon"]
          args: ["server"]
          name: simple-directory
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: 500m
          volumeMounts:
            - mountPath: /webapp/security
              name: simple-directory-security

      volumes:
        - name: simple-directory-security
          persistentVolumeClaim:
            claimName: simple-directory-security
