apiVersion: v1
kind: ConfigMap
metadata:
  name: config-global
data:
  base-url: http://192.168.49.2:32000
  secret: azerty
  data-fair-api-key: dTo4Z21YOHdjYlY6U3M0akREU1pkRERqOHBnRnFQUVpf
  mails-transport: '{"host": "http://192.168.49.2:32000/mails"}'
